paiji2_social/urls.py
from django.conf.urls import url  # , patterns
from django.contrib.auth.decorators import login_required

from .views import (
    MessageListView,
    MessageCreateView,
    MessageEditView,
    MessageDeleteView,
    CommentCreateView,
    GroupView,
    GroupMembersView,
    GroupNewsView,
    UserDirectoryView,
    GroupDirectoryView,
)
from .feeds import LatestEntriesFeed

urlpatterns = [
    # Message List (homepage)
    url(
        r'^$',
        MessageListView.as_view(),
        name='index',
    ),
    # Message
    url(
        r'^add$',
        login_required(MessageCreateView.as_view()),
        name="newsfeed-add",
    ),
    url(
        r'^edit/(?P<pk>[0-9]+)/$',
        login_required(MessageEditView.as_view()),
        name="newsfeed-edit",
    ),
    url(
        r'^delete/(?P<pk>[0-9]+)/$',
        login_required(MessageDeleteView.as_view()),
        name="newsfeed-delete",
    ),
    url(
        r'^comment/(?P<on_message>[0-9]+)/$',
        login_required(CommentCreateView.as_view()),
        name="comment-add"
    ),

    # User Directory
    url(
        r'^directory/$',
        login_required(UserDirectoryView.as_view()),
        name='directory',
    ),

    # Group Directory
    url(
        r'^groups/$',
        login_required(GroupDirectoryView.as_view()),
        name='groups',
    ),

    # Group
    url(
        r'^(?P<slug>[\w-]+)/dashboard$',
        login_required(GroupView.as_view()),
        name="workgroup-view",
    ),

    # Group Members
    url(
        r'^(?P<slug>[\w-]+)/members$',
        login_required(GroupMembersView.as_view()),
        name="workgroup-members",
    ),

    # Group News
    url(
        r'^(?P<slug>[\w-]+)/news$',
        login_required(GroupNewsView.as_view()),
        name="workgroup-news",
    ),

    # Feeds
    url(
        r'^feeds/latest$',
        login_required(LatestEntriesFeed()),
        name="feed-latest",
    ),
]

paiji2_social/models.py
from django.db import models

# from django.utils import timezone
from django.contrib.auth import get_user_model
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from backbone_calendar.models import Calendar


try:
    User = get_user_model()
except:
    User = settings.AUTH_USER_MODEL


class PostType(models.Model):
    description = models.CharField(
        _('description'),
        max_length=50,
        blank=False,
    )

    def __unicode__(self):
        return self.description

    class Meta:
        verbose_name = _('post type')
        verbose_name_plural = _('post types')


class GroupCategory(models.Model):
    name = models.CharField(
        _('name'),
        max_length=50,
        unique=True,
    )

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('group category')
        verbose_name_plural = _('group categories')


class Group(models.Model):
    name = models.CharField(
        _('name'),
        max_length=50,
        unique=True,
        blank=False
    )

    slug = models.SlugField()

    category = models.ForeignKey(
        GroupCategory,
        null=False,
        verbose_name=_('category'),
    )

    createdOn = models.DateTimeField(
        _('creation date'),
        auto_now_add=True,
        null=False,
        blank=False,
    )

    deletedOn = models.DateTimeField(
        _('deletion date'),
        null=True,
        blank=True,
    )

    logo = models.ImageField(
        _('logo'),
        upload_to='groups/logo',
        null=True,
    )

    newsfeed = models.URLField(
        _('newsfeed'),
        blank=True,
    )

    calendar = models.OneToOneField(
        Calendar,
        verbose_name=_('calendar'),
        related_name='group',
        null=True,
    )

    def get_absolute_url(self):
        return reverse('workgroup-view', kwargs={
            'slug': self.slug,
        })

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')


class Bureau(models.Model):
    createdDate = models.DateTimeField(
        _('tenure beginning date'),
        auto_now_add=True,
        null=False,
    )

    endDate = models.DateTimeField(
        _('tenure end date'),
        null=True,
        blank=True,
    )

    group = models.ForeignKey(
        Group,
        verbose_name=_('group'),
        blank=False,
        related_name='bureaus',
    )

    def currentBureauExist(self):
        if self.endDate is None:
            nb_boards = Bureau.objects.filter(
                group=self.group,
                endDate=None,
            ).count()
            return nb_boards > 0
        return False
    currentBureauExist.short_description = _('Does it exist ?')

    def is_current(self):
        return self.endDate is not None
    is_current.short_description = _('Is it current ?')

    def clean(self):
        if self.currentBureauExist():
            raise ValidationError(_(
                """Another current Bureau exists already, """
                """update its tenure end date (endDate) """
                """before setting a new Bureau."""
            ))

    def __unicode__(self):
        return self.group.name

    class Meta:
        verbose_name = _('Bureau')
        verbose_name_plural = _('Bureaux')
        ordering = ('group__category', 'group__name', '-createdDate')


class Post(models.Model):
    utilisateur = models.ForeignKey(
        User,
        verbose_name=_('user'),
        related_name='posts',
    )

    bureau = models.ForeignKey(
        Bureau,
        verbose_name=_('Bureau'),
        related_name='members',
    )

    description = models.TextField(
        _('description'),
        blank=True,
    )

    postType = models.ForeignKey(
        PostType,
        verbose_name=_('post type'),
        null=False,
    )

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        unique_together = ('bureau', 'postType',)


class Message(models.Model):
    author = models.ForeignKey(
        User,
        verbose_name=_('author'),
        related_name='message',
    )

    pubDate = models.DateTimeField(
        _('publication date'),
        auto_now_add=True,
        null=False,
    )

    title = models.CharField(
        _('title'),
        max_length=140,
        blank=False,
    )

    content = models.TextField(
        _('content'),
        blank=False,
    )

    public = models.BooleanField(
        verbose_name=_('readable by unregistered visitors'),
        default=False,
    )

    IMPORTANCE_LEVEL = (
        (0, _('Normal')),
        (1, _('Priority')),
    )

    group = models.ForeignKey(
        Group,
        verbose_name=_('group'),
    )

    importance = models.IntegerField(
        _('importance level'),
        choices=IMPORTANCE_LEVEL,
        blank=False,
        default=0,
    )

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('message')
        verbose_name_plural = _('messages')
        ordering = ('group__name', '-pubDate', )


class Comment(models.Model):
    author = models.ForeignKey(
        User,
        verbose_name=_('author'),
        related_name='comment',
    )

    message = models.ForeignKey(
        Message,
        verbose_name=_('message'),
        related_name='comment'
    )

    pubDate = models.DateTimeField(
        _('publication date'),
        null=False,
    )

    content = models.CharField(
        _('content'),
        max_length=140,
        blank=False,
    )

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')
        ordering = ('message', '-pubDate', )

paiji2_social/forms.py
from django import forms
from django.utils.translation import ugettext as _

from .models import Comment, Message
from tinymce.widgets import TinyMCE


class CommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = _('Write a comment...')

    class Meta:
        model = Comment
        fields = ('content', )


class MessageForm(forms.ModelForm):

    def __init__(self, groups, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = groups

    class Meta:
        model = Message
        fields = (
            'group',
            'title',
            'content',
            'public',
        )
        widgets = {
            'content': TinyMCE(attrs={'cols': 80, 'rows': 20}),
        }

paiji2_social/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.views import generic
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.contrib import messages
from django.http import HttpResponseNotFound
from django.contrib.auth import get_user_model
from django.db.models import Q

from .models import Message, Comment, Group
from .forms import CommentForm, MessageForm
from django.conf import settings


class MessageListView(generic.ListView):
    model = Message
    paginate_by = 5
    context_object_name = 'news'
    template_name = 'social/index.html'

    def get_queryset(self):
        qs = super(MessageListView, self).get_queryset()
        if not self.request.user.is_authenticated():
            qs = qs.filter(public=True)

        return qs.order_by('-pubDate').select_related('author')


class MessageFormMixin(object):

    form_class = MessageForm

    def get_form_kwargs(self):
        kwargs = super(MessageFormMixin, self).get_form_kwargs()
        kwargs.update({
            'groups': Group.objects.filter(
                bureaus__members__utilisateur=self.request.user,
                )
        })
        return kwargs


class MessageCreateView(MessageFormMixin, generic.CreateView):
    model = Message
    template_name = 'social/message_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(MessageCreateView, self).form_valid(form)

    def get_success_url(self):
        messages.success(
            self.request,
            _('Your request has been saved successfully :P'),
        )
        return reverse('index')


class OwnershipMessageCheck(object):
    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update Messages """
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseNotFound(
                _('Rezo is not hacked. You don\'t have the permission xD')
            )
        return super(OwnershipMessageCheck, self).dispatch(
            request, *args, **kwargs
        )


class MessageEditView(
                     OwnershipMessageCheck,
                     MessageFormMixin,
                     generic.UpdateView
                    ):
    model = Message
    template_name = 'social/message_form.html'
    message_update = _(
        'Your Message has been updated, it will be refreshed in a moment'
    )

    def get_success_url(self):
        messages.success(
            self.request,
            self.message_update,
        )
        return reverse('index')


class MessageDeleteView(OwnershipMessageCheck, generic.DeleteView):
    model = Message
    template_name = 'social/message_confirm_delete.html'
    message_delete = _(
        'Your Message has been removed, it will be refreshed in a moment'
    )

    def get_success_url(self):
        messages.success(
            self.request,
            self.message_delete,
        )
        success_url = self.request.POST.get('next')
        return success_url if success_url != '' else reverse('index')


class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    http_method_names = ['post']

    def form_valid(self, form):
        # TODO: it should check that the message exists before
        #       showing the form
        message = Message.objects.get(id=self.kwargs['on_message'])
        form.instance.author = self.request.user
        form.instance.message = message
        # TODO use auto_now_add=True
        form.instance.pubDate = timezone.now()
        return super(CommentCreateView, self).form_valid(form)

    def get_success_url(self):
        messages.success(
            self.request,
            _("Your comment has been successfully saved."),
        )
        success_url = self.request.POST.get('next')
        return success_url if success_url != '' else reverse('index')


class GroupView(generic.DetailView):
    model = Group
    template_name = 'social/group_detail.html'


class GroupMixin(object):

    def dispatch(self, *args, **kwargs):
        self.group = get_object_or_404(Group, slug=kwargs['slug'])
        return super(GroupMixin, self).dispatch(*args, **kwargs)

    def get_context_data(self):
        cd = super(GroupMixin, self).get_context_data()
        cd['group'] = self.group
        return cd


class GroupNewsView(GroupMixin, generic.ListView):
    model = Message
    template_name = 'social/news_list.html'
    context_object_name = 'news'
    paginate_by = 8

    def get_queryset(self):
        qs = super(GroupNewsView, self).get_queryset()
        qs = qs.filter(group=self.group)
        qs = qs.order_by(
            '-pubDate'
        ).select_related(
            'author'
        )
        return qs


class GroupMembersView(GroupMixin, generic.ListView):
    model = get_user_model()
    template_name = 'social/member_list.html'
    context_object_name = 'members'

    def get_queryset(self):
        qs = super(GroupMembersView, self).get_queryset()
        qs = qs.filter(posts__bureau__group=self.group)
        return qs


class UserDirectoryView(generic.ListView):
    model = get_user_model()
    context_object_name = 'users'
    ordering = ['last_name', 'first_name', 'username']
    template_name = 'social/directory.html'
    paginate_by = 20

    def get_queryset(self):
        if 'q' in self.request.GET:
            query = self.request.GET['q']
            words = query.split(' ')
            Qobj = Q()
            filtered = False
            for word in words:
                if word != '':
                    filtered = True
                    Qobj &= (
                        Q(first_name__icontains=word) |
                        Q(last_name__icontains=word) |
                        Q(username__icontains=word) |
                        Q(email__icontains=word)
                    )
                    if (
                        hasattr(settings, 'CI_TEST') and
                        settings.CI_TEST
                    ):
                        pass
                    else:
                        Qobj |= Q(room__icontains=word)
            if filtered:
                return self.model.objects.filter(Qobj)
        return super(UserDirectoryView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super(UserDirectoryView, self).get_context_data(**kwargs)
        q = self.request.GET.get('q', '')
        context.update({'q': q})
        return context


class GroupDirectoryView(generic.ListView):
    model = Group
    context_object_name = 'groups'
    ordering = ['name', 'category', 'createdOn']
    template_name = 'social/groups.html'

paiji2_social/templates/social/comment_area.html
{% load bootstrap3 %}
{% load i18n %}
{% load profile %}

<ul class="list-unstyled comments">
	{% for comment in comments %}

		<li>

            {% profile_link comment.author %}

            {% if request.user.is_authenticated %}
                <div class="pull-right">
                    {% with subject='[social] '|add:_('About')|add:' : "'|add:comment.content|add:'"' %}
                    {% mail_link comment.author '' subject %}
                    {% endwith %}
                </div>
            {% endif %}

            : {{ comment.content|urlize }}

    		<span class="text-muted">
                <small>
                    {% blocktrans with TimeSince=comment.pubDate|timesince %}{{ TimeSince }} ago{% endblocktrans %}
                </small>
            </span>

        </li>

        <li>
            <hr/>
        </li>

	{% endfor %}

	{% if request.user.is_authenticated and comments|length < 20 %}
        <li>
            <form method="post" action="{% url 'comment-add' on_message.id %}">
                {% csrf_token %}
                {% bootstrap_field form.content show_label=False %}
                {% buttons %}
                    <input style="display:none; position: absolute; left: -9999px; width: 1px; height: 1px;" type="submit" value="Sent" class="btn btn-success" />
                {% endbuttons %}
                <input type="hidden" value="{{ request.get_full_path }}" name="next" />
                <div class="clearfix"></div>
            </form>
        </li>
    {% endif %}
</ul>

paiji2_social/templates/social/directory.html
{% extends "social/directory_base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load profile %}
{% load gravatar %}

{% block title %}

{% trans 'User Directory' %}
{% if q %}
	| {{ q }}
{% endif %}

{% endblock %}

{% block usersbtnclass %}
active
{% endblock %}

{% block form %}

<div class="row">
    <div class="col col-md-12">
        <h2>{% trans 'User Directory' %}</h2>
	</div>
</div>


<div class="row">
    <div class="col col-md-12 centered">
        <form role="search" method="GET"
        name="search" action="{{ request.path }}" >
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-search"></i>
                    {% trans 'search' %}
                </span>
                <input class="form-control" name="q" title="search" type="text" value="{{ q }}"/>
            </div>
        </form>
        <br/>
	</div>
</div>

{% endblock %}

{% block results %}

{% if is_paginated %}
<div class="row">
    <div class="col col-md-12 centered pagination-container">
        {% bootstrap_pagination page_obj url=request.get_full_path %}
	</div>
</div>
{% endif %}

<div class="row">
<div class="col col-md-12">
<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>{% trans 'Profile' %}/{% trans 'Pseudo' %}</th>
            <th>{% trans 'First name' %}</th>
            <th>{% trans 'Last name' %}</th>
            <th>{% trans 'School' %}/{% trans 'Class' %}</th>
            <th>{% trans 'Room' %}</th>
            <th>{% trans 'Email' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
            <td>
                <a class="logo"
                title="{% trans 'view profile' %}"
                href="{% profile_url user %}" >
                    {% gravatar user.email 30 %}
                </a>
                <a title="{% trans 'view profile' %}"
                href="{% profile_url user %}" >
									{{ user.username }}
                </a>
            </td>
            <td><strong>{{ user.first_name }}</strong></td>
            <td>
                    <p class="text-uppercase">
                        {{ user.last_name }}
                    </p>
            </td>
            {% if user.get_rezo %}
                <td>
                    {{ user.get_rezo.ecole }}
                    {{ user.get_rezo.precisionecole }}
                </td>
                <td>{{ user.get_room }}</td>
            {% else %}
                <td></td>
                <td></td>
            {% endif %}
            <td>
                <a href="mailto:{{ user.email|urlencode }}"
                title="{{ _('Send a mail to')|add:' '|add:user.first_name|add:' '|add:user.last_name }}"
                >
                    {{ user.email }}
                </a>
            </td>
        </tr>
		{% empty %}
		<tr class="inactive">
			<td><span class="label label-defaul label-danger">{% trans 'no result' %}</span></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
    {% endfor %}
    </tbody>
</table>
</div><!-- col -->
</div><!-- row -->

{% if is_paginated %}
<div class="row">
    <div class="col col-md-12 centered pagination-container">
        {% bootstrap_pagination page_obj url=request.get_full_path %}
	</div>
</div>
{% endif %}

{% endblock %}

paiji2_social/templates/social/directory_base.html
{% extends "home/base.html" %}
{% load i18n %}
{% block layout %}

<div class="row">
    <div class="col-md-2 col-sx-1 dark-text">
			{% block nav %}
					<div class="sidebar-nav navbar-collapse">
						<ul class="nav">
							<li>
								<a class="btn btn-default {% block usersbtnclass %}{% endblock %}" href="{% url 'directory' %}">
									<i class="fa fa-user"></i>
									{% trans 'Users' %}</a>
									<br/>
							</li>
							<li>
								<a class="btn btn-default {% block groupsbtnclass %}{% endblock %}" href="{% url 'groups' %}">
									<i class="fa fa-users"></i>
									{% trans 'Groups' %}
								</a>
								<br/>
							</li>
						</ul>
					</div>
			{% endblock %}
		</div>
		<div class="col-md-10">
					{% block form %}{% endblock %}
		</div>
</div>

<div class="row">
	<div class="col-md-12">
		{% block results %}{% endblock %}
	</div>
</div>
			
{% endblock %}

paiji2_social/templates/social/group_base.html
{% extends "home/layout_master_detail.html" %}
{% load i18n %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'social/css/social.css' %}" />
{% endblock %}

{% block master %}
<div class="sidebar-nav navbar-collapse">
	<ul class="nav" id="side-menu">
		<li>
			<a class="active" href="{% url 'workgroup-view' slug=group.slug %}"><i class="fa fa-calendar fa-fw"></i>{% trans 'Calendar' %}</a>
		</li>
		<li>
			<a class="active" href="{% url 'workgroup-news' slug=group.slug %}"><i class="fa fa-rss fa-fw"></i>{% trans 'News' %}</a>
		</li>
		<li>
			<a class="active" href="#"><i class="fa fa-envelope fa-fw"></i>{% trans 'Mailing lists' %} ({% trans 'coming soon' %})</a>
		</li>
		<li>
			<a class="active" href="{% url 'workgroup-members' slug=group.slug %}"><i class="fa fa-user fa-fw"></i>{% trans 'Members' %}</a>
		</li>
	</ul>
</div>
{% endblock %}

paiji2_social/templates/social/group_detail.html
{% extends 'social/group_base.html' %}
{% load i18n %}
{% load backbone_calendar %}
{% load bootstrap3 %}

{% block title %}{% trans 'Dashboard' %}{% endblock %}



{% block content %}
<div id="calendar"></div>

<div class="well pull-right">
    <a href="{{ group.calendar.get_icalendar_url }}"
        class="btn btn-success">
        {% bootstrap_icon 'download' %}
        {% trans 'Download iCalendar file (.ics)' %}
    </a>
</div>
{% get_calendar_display calendar=group.calendar as display %}
{{ display.print_list_agendas }}
{% endblock %}

{% block style %}
{% print_stylesheet_links %}
{% endblock %}

{% block js %}
{% print_javascript_scripts %}
{% get_calendar_display calendar=group.calendar as display %}
<script type="text/javascript">
var calendar = {{ display.to_json }};
</script>
{% endblock %}

paiji2_social/templates/social/groups.html
{% extends "social/directory_base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load profile %}
{% load gravatar %}

{% block title %}
{% trans 'Groups' %}
{% endblock %}

{% block form %}

<div class="row">
    <div class="col col-md-12">
        <h2>{% trans 'Group Directory' %}</h2>
	</div>
</div>

{% endblock %}

{% block groupsbtnclass %}
active 
{% endblock %}

{% comment %}
<div class="row">
    <div class="col col-md-12 centered">
        <form role="search" method="GET"
        name="search" action="{{ request.path }}" >
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-search"></i>
                    {% trans 'search' %}
                </span>
                <input class="form-control" name="q" title="search" type="text" value="{{ q }}"/>
            </div>
        </form>
        <br/>
	</div>
</div>
{% endcomment %}

{% block results %}

{% if is_paginated %}
<div class="row">
    <div class="col col-md-12 centered pagination-container">
        {% bootstrap_pagination page_obj %}
	</div>
</div>
{% endif %}

<div class="row">
{% for group in groups %}
    <div class="col-md-3 col-sm-4">
        <div class="well">
            <div class="thumbnail">
                <a class="logo"
                title="{% trans 'view group detail' %}"
                href="{{ group.get_absolute_url }}" >
                    <img alt="{{ group.name|add:' '|add:_('logo') }}"
                    width="100" src="{{ group.logo.url }}"/>
                </a>
            </div><!-- thumbnail --> 
            <div class="caption">
                <h3>
                    <a title="{% trans 'view group detail' %}"
                    href="{{ group.get_absolute_url }}" >
                       {{ group.name }}
                    </a>
                    <small class="pull-right text-muted">{{ group.category }}</small>
                </h3>
            </div><!-- caption --> 
        </div><!-- well -->
    </div><!-- col -->
{% endfor %}
</div><!-- row -->

{% comment %}
<div class="row">
<div class="col col-md-12">
<table class="table table-striped">
    <thead>
        <tr>
            <th>{% trans 'Group' %}</th>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Category' %}</th>
            <th>{% trans 'Creation date' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for group in groups %}
        <tr>
            <td>
                <a class="logo"
                title="{% trans 'view group detail' %}"
                href="{{ group.get_absolute_url }}" >
                    <img alt="{{ group.name|add:' '|add:_('logo') }}"
                    width="100" src="{{ group.logo.url }}"/>
                </a>
            </td>
            <td>
                <a title="{% trans 'view group detail' %}"
                href="{{ group.get_absolute_url }}" >
                   {{ group.name }}
                </a>
            </td>
            <td>{{ group.category }}</td>
            <td>
                {{ group.createdOn }}
            </td>
        </tr>
		{% empty %}
		<tr class="inactive">
			<td><span class="label label-defaul label-danger">{% trans 'no result' %}</span></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
    {% endfor %}
    </tbody>
</table>
</div>
</div>
{% endcomment %}

{% if is_paginated %}
<div class="row">
    <div class="col col-md-12 centered pagination-container">
        {% bootstrap_pagination page_obj %}
	</div>
</div>
{% endif %}

{% endblock %}

paiji2_social/templates/social/index.html
{% extends "home/layout_three_columns.html" %}
{% load staticfiles i18n %}

{% block title%}{#Translators: "accueil"#}{% trans 'Home' %}{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'social/css/social.css' %}" />
{% endblock %}

{% block content %}
{% include "social/news-feed.html" %}
{% endblock %}

{% block js %}

{% endblock %}

paiji2_social/templates/social/message_form.html
{% extends "home/layout_three_columns.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block style %}
{{ form.media }}
{% endblock %}

{% block title %}
    {% if form.instance and form.instance.pk %}
    {% trans 'Edit article' %}
    {% else %}
    {% trans 'Write article' %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="well">
        {% if form.instance and form.instance.pk %}
        <h3>{% trans 'Edit article' %}</h3>
        {% else %}
        <h3>{% trans 'Write article' %}</h3>
        {% endif %}


        {% if request.user.get_related_groups|length > 0 %}
        <form action="{{ request.get_full_path }}" method="post" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label>{% trans 'Author' %}</label>
                <p>{{ request.user.first_name }} ({{ request.user.email }})</p>
            </div>

            <div class="form-group">
                <label for="id_group">{% trans 'Group' %}</label>
                {% bootstrap_field form.group show_label=False %}

                <label for="id_title">{% trans 'Title' %}</label>
                {% bootstrap_field form.title show_label=False %}

                <label for="id_public">{% trans 'Visibility option' %}</label>
                {% bootstrap_field form.public show_label=False %}

                <label for="id_content">{% trans 'Content' %}</label>
                {% bootstrap_field form.content show_label=False %}
            </div>

            <input type="hidden" value="{{ request.META.HTTP_REFERER }}" name="next" />
            <br />
            {% buttons %}
                <button type="submit" class="btn btn-success pull-right">
                    {% if form.instance and form.instance.pk %}
                        {% trans 'Save' %}
                    {% else %}
                        {% trans 'Publish' %}
                    {% endif %}
                </button>
            {% endbuttons %}
            <div class="clearfix"></div>
        </form>
        {# there is way to bypass a bug #}
        <p>
            {{ 'Si le bouton "publier" ne fonctionne pas, appuyer sur "F5" (recharger la page) puis "Quitter la page" dans la fenêtre de dialogue, avant de réappuyer sur le bouton "publier".' }}
        </p>
        {% else %}

        {% trans 'You are not registered as a staff of a group (association/club/list), please contact rezo or the bureau of your group to register you as a staff.' %}

        {% endif %}
    </div>
{% endblock %}

paiji2_social/templates/social/news_list.html
{% extends 'social/group_base.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% trans 'News' %}{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'social/css/social.css' %}" />
{% endblock %}

{% block content %}
{% include "social/news-feed.html" %}
{% endblock %}